### ISSUE TITLE
User can play a full, single round of posele

### ISSUE THREAD

**Issue by tymonaghan** [team-posele/posele#21]
- [ ] press PLAY
- [ ] see instructions and warning (#18)
- [ ] display pose w. timer (#19)
- [ ] open camera and auto-snap after timer (#20)
